apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversao
  template:
    metadata:
      labels:
        app: conversao
    spec:
      containers:
      - name: conversao
        image: matwolbec/conversao-temperatura:v1
---
apiVersion: v1
kind: Service
metadata:
  name: conversor
spec:
  selector:
    app: conversao
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort